# Generated by Django 3.2.3 on 2021-06-01 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KindOfPokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('attack', models.IntegerField()),
                ('block', models.IntegerField()),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='poke.kindofpokemon')),
            ],
        ),
    ]
